{ config, pkgs, ... }: 

{
    # Import other configuration modules
    # (hardware-configuration.nix is autogenerated upon installation)
    # paths in nix expressions are always relative the file which defines them
    imports =
        [
            ./hardware-configuration.nix
           # ./my-dev-tools.nix
           # ./my-desktop-env.nix
           # ./etc.nix
        ];

    # Bootloader 
    boot.loader.systemd-boot.enable = true;    
    
    # Name your host machine
    networking.hostName = "nixos01"; 

    # Set your time zone.
    time.timeZone = "Europe/Utrecht";

    # Enter keyboard layout
    services.xserver.layout = "de";
    services.xserver.xkbVariant = "altgr-intl";
    
    #Docker Stuff 
    virtualisation.docker.enable = true;
    virtualisation.docker.enableOnBoot = true;    

    # Define user accounts
    users.users = 
        { 
            odeinhart = 
            {
                home = "/home/odeinhart";
                extraGroups = [ "wheel" "networkmanager" "docker" ];
                isNormalUser = true;
                uid = 1000;
            };
        };
    
    # Install some packages
    environment.systemPackages = 
            with pkgs; 
            [
                ddate
                testdisk
                zsh
                vim
                oh-my-zsh
                docker
            ]; 
 
    # Enable the OpenSSH daemon
    services.openssh.enable = true;
    
}

